#!/usr/bin/env python3
"""Generate app/src/main/java/app/vela/ui/icons/Sym.kt from Material Symbols Rounded (Apache 2.0).

Every icon name the app references as Icons.<Style>.<Name> gets two ImageVectors: Sym.<Name>
(filled, the rounded set's FILL 1) and SymOutlined.<Name> (FILL 0), drawn from the official SVGs on
fonts.gstatic.com. Run after adding an icon to the app: python3 scripts/gen-symbols.py [--rewrite]
(--rewrite also swaps Icons.Default/Filled/Rounded/AutoMirrored.Filled -> Sym and Icons.Outlined ->
SymOutlined in the sources).
"""
import os, re, sys, urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "app/src/main/java")
OUT = os.path.join(SRC, "app/vela/ui/icons/Sym.kt")
PATTERN = re.compile(r"(?:androidx\.compose\.material\.icons\.)?Icons\.(Default|Filled|Outlined|Rounded|AutoMirrored\.(?:Filled|Outlined))\.([A-Za-z0-9]+)")
SPECIAL = {"Clear": "close", "BookmarkBorder": "bookmark", "StarBorder": "star", "UTurnLeft": "u_turn_left"}
ALWAYS_OUTLINE = {"BookmarkBorder", "StarBorder"}

def snake(n):
    return SPECIAL.get(n) or re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", n).lower()

def fetch(sym, fill):
    url = f"https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsrounded/{sym}/{'fill1' if fill else 'default'}/24px.svg"
    try:
        with urllib.request.urlopen(url, timeout=20) as r:
            return re.findall(r'<path d="([^"]+)"', r.read().decode())
    except Exception:
        return None

files = []
names, mirrored = set(), set()
for d, _, fs in os.walk(SRC):
    for f in fs:
        if f.endswith(".kt") and f != "Sym.kt":
            p = os.path.join(d, f); s = open(p).read()
            found = PATTERN.findall(s)
            if found: files.append(p)
            for style, n in found:
                names.add(n)
                if style.startswith("AutoMirrored"): mirrored.add(n)

lines = ["package app.vela.ui.icons", "",
         "// GENERATED by scripts/gen-symbols.py from Material Symbols Rounded (Apache License 2.0,",
         "// fonts.google.com/icons). Do not edit by hand; rerun the script.", "",
         "import androidx.compose.ui.graphics.Color", "import androidx.compose.ui.graphics.SolidColor",
         "import androidx.compose.ui.graphics.vector.ImageVector", "import androidx.compose.ui.graphics.vector.addPathNodes",
         "import androidx.compose.ui.unit.dp", ""]
missing = []
blocks = {"Sym": [], "SymOutlined": []}
for n in sorted(names):
    sym = snake(n)
    for obj, fill in (("Sym", n not in ALWAYS_OUTLINE), ("SymOutlined", False)):
        paths = fetch(sym, fill)
        if not paths:
            missing.append(f"{n}->{sym}"); break
        args = ", ".join('"' + p + '"' for p in paths)
        blocks[obj].append(f'    val {n}: ImageVector by lazy {{ symbol("{n}", {"true" if n in mirrored else "false"}, {args}) }}')
for obj in ("Sym", "SymOutlined"):
    lines.append(f"object {obj} {{"); lines += blocks[obj]; lines.append("}"); lines.append("")
lines += ["private fun symbol(name: String, autoMirror: Boolean, vararg paths: String): ImageVector =",
          "    ImageVector.Builder(name = \"Sym.$name\", defaultWidth = 24.dp, defaultHeight = 24.dp,",
          "        viewportWidth = 960f, viewportHeight = 960f, autoMirror = autoMirror)",
          "        .addGroup(translationY = 960f)",
          "        .apply { paths.forEach { addPath(pathData = addPathNodes(it), fill = SolidColor(Color.Black)) } }",
          "        .clearGroup()", "        .build()", ""]
os.makedirs(os.path.dirname(OUT), exist_ok=True)
open(OUT, "w").write("\n".join(lines))
print(f"{len(names)} icons, {len(files)} files; missing: {missing}")

if "--rewrite" in sys.argv:
    have = {n for n in names if not any(m.startswith(n + "->") for m in missing)}
    for p in files:
        s = open(p).read()
        def sub(m):
            style, n = m.group(1), m.group(2)
            if n not in have: return m.group(0)
            return ("SymOutlined." if "Outlined" in style else "Sym.") + n
        s2 = PATTERN.sub(sub, s)
        if s2 == s: continue
        if "Icons." not in s2:
            s2 = re.sub(r"^import androidx\.compose\.material\.icons\..*\n", "", s2, flags=re.M)
        imports = [i for i in ("Sym", "SymOutlined") if re.search(rf"\b{i}\.", s2) and f"import app.vela.ui.icons.{i}\n" not in s2]
        if imports:
            s2 = re.sub(r"^(package [^\n]+\n)", lambda m: m.group(1) + "\n" + "".join(f"import app.vela.ui.icons.{i}\n" for i in imports), s2, count=1)
        open(p, "w").write(s2)
    print("rewrote", len(files), "files")
